name = "kanily-site"
compatibility_date = "2026-02-19"

# This configures the Worker to serve the static assets
# built by Eleventy.
[assets]
directory = "./"

# Since you have a 404.html file, this tells Cloudflare to serve it
# when a requested file is not found
not_found_handling = "404-page"